### ISSUE TITLE
 Colors should resemble vlaanderen.be style

### ISSUE THREAD

**Issue by koenmetsu** [Informatievlaanderen/registry-documentation#1]
```css
[data-md-color-primary=yellow] .md-header {
    background-color: #FFE615;
    color: #000;
}
```

something like this.
